trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  acrName: 'youracr'
  imageName: 'user-service'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    python -m venv venv
    source venv/bin/activate
    pip install -r requirements.txt
    echo "Running tests..."
    # Add your test commands here
  displayName: 'Run tests'

- task: Docker@2
  inputs:
    containerRegistry: '$(acrName)'
    repository: '$(imageName)'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)
      latest

- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscription: 'YourAzureSubscription'
    azureResourceGroup: 'myResourceGroup'
    kubernetesCluster: 'myAKSCluster'
    namespace: 'default'
    command: 'apply'
    useConfigurationFile: true
    configuration: |
      user-service-deployment.yaml
      user-service-service.yaml
